### ISSUE TITLE
Exactly what I was looking for | License request

### ISSUE THREAD

**Issue by nuttyartist** [Open-App-Library/QBasicHtmlExporter#1]
Hello! Thanks for this repo!

This is exactly what I've been looking for. QTextDocument outputting inline styling is so annoying. Their `QTextDocument::toMarkdown()` has a bug (https://bugreports.qt.io/browse/QTBUG-123133) where it converts HTML to incorrect markdown, and since `QTextDocument::toHtml` doesn't output normal HTML I can't use other parsers to fix this problem.

I'm the author of the open-source note-taking app Notes (https://github.com/nuttyartist/notes) and now I'm working on a new (closed-source, for now) project called Plume (https://www.get-plume.com/).

Could you please add a license to this repo, so I could incorporate it? And can it please be a permissive one?

**Comment by DougBeney** [comment]
Glad you've found it of use! This library is something I wrote for Vibrato Notes, an open source note taking app I was working on and then kind of just hadn't had the time to finish (but it's still on my mind!) 

Just added a GPL3 license. Thanks! 

A fair warning that this was written for Qt5. I haven't yet tried out Qt6 so I couldn't tell you if any porting work needs to be done.

**Comment by nuttyartist** [comment]
I've heard about Vibrato Notes before and was always searching for binaries to download, I hope you get to it someday, it's always nice to learn from other Qt apps.

Can you consider changing the license to a more permissive one, please? I won't be able to use your library in my closed-source code (actually, even in my MPL open-sourced one, since I'll be required to change the license to GPL as well). I'm using the Mozilla Public License (MPL) for my previous note-taking app, which is more permissive yet still requires people to release source code changes, if there were any, to the code being used. Would you consider changing it to that or other permissive license?

> A fair warning that this was written for Qt5. I haven't yet tried out Qt6 so I couldn't tell you if any porting work needs to be done.

Gotcha, I'll try my best to make it work.

**Comment by DougBeney** [comment]
Sure thing. LGPL work for you?

**Comment by nuttyartist** [comment]
If I understand this correctly, LGPL would require me to dynamically load `QBasicHtmlExporter`, so people could replace and link other versions of it with the object files of my app, if I link my app statically (which I intend to). I know I need to do this for Qt but I'm not sure how to do it with `QBasicHtmlExporter`. I'm sorry to be annoying, I'm just trying to save myself a legal headache in the future. MPL would require me only to release changes to the source code of `QBasicHtmlExporter` which is much easier to do (and much less of a legal headache). And did I say you'll get credit in the app's About window 😃 ?

**Comment by DougBeney** [comment]
Gotcha, I think you're right. I swapped it over to MPL :+1:

**Comment by nuttyartist** [comment]
Thanks a lot! I very much appreciate that.

**Comment by DougBeney** [comment]
Of course! I look forward to seeing how your app progresses and let me know if you need anything else. 
Feel free to peruse the Open App Library Github. There were a few various libraries and projects and here, note taking related.

**Comment by nuttyartist** [comment]
Of course! I'll keep you posted on Twitter.

Just integrated `QBasicHtmlExporter` and I seem to have the same issue where the tags are opening/closing not in the right place.

For this Qt's HTML:

```
Qt's HTML:  "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\nhr { height: 1px; border-width: 0; }\nli.unchecked::marker { content: \"\\2610\"; }\nli.checked::marker { content: \"\\2612\"; }\n</style></head><body style=\" font-family:'.AppleSystemUIFont'; font-size:13pt; font-weight:400; font-style:normal;\">\n<p style=\" margin-top:8px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This is <span style=\" font-weight:700; text-decoration: line-through;\">some</span> text here let's see how it goes</p></body></html>"
```

`QBasicHtmlExporter` returns:

```
"<p>This is <strong><del>some</strong></del> text here let's see how it goes</p>"
```

Where I expect it to return:

```
"<p>This is <del><strong>some</strong></del> text here let's see how it goes</p>"
```

Do you know what's going on? I assume it should be easier for me to hack this then before since now I get both opening and closing tags (compared to just Markdown), but wondering if you know a simpler, more intuitive solution?

**Comment by nuttyartist** [comment]
Well, a simple change did the trick. I simply replaced the `append` with `prepend` for `closing_tags`. I'll send a PR soon (with Qt 6 support and other changes).

```c++
closing_tags << "</del>";
```
```c++
closing_tags.prepend("</del>");`
```
